spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  redis:
#    host: ENC(uLUqtuUMvM2O39Rk325+lx40jULQdYBm)
#    port: 6379

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ENC(5X5YCmAdK2dp46FL51OKR6mjrX4dSM1Kf39IURnNmCSKj6hImsT0P8O0xGbg4vxBKQmEGtJdt1hYMi57zJAJlxjCsEehyYypOVL6Lv8xd0rfyDhImXCmvLMqnjRvr/33)
    username: ENC(FVL5dE5L0qcJDH0nuGO1h3KUe/u5r0ga)
    password: ENC(Gg7F8JPQE7GDham3ex4TU8K5UVmoNxUd)