spring:
#  redis:
#    host: ENC(uLUqtuUMvM2O39Rk325+lx40jULQdYBm)
#    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #이 아래로 주석처리하면 H2 인메모리
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #      hibernate:
  #        format_sql: true
  #  logging.level:
  #    org.hibernate.SQL: debug